#!/bin/sh

out=README.md

cat <<EOF >$out
Overview
========

DEFCON 21 badge hacking.  Work in progress.

Details
=======
On the floor is a cypher for the 1930's novelette "Chain of Death".
It reads "KEYWORDHMODOXIAN".  Maybe an O is missing. Maybe we screwed it up.

https://www.defcon.org/1o57/dc21/homodoxian/ is a clue.

https://www.defcon.org/1o57/dc21/orrery/ is a clue.

Badges have playing card designs varrying by suit and number.  On the
back of each card is a string of numbers.  These appear to be 2-digit
numbers ranging from 01-26 which are ordinals into a mapping of
the alphabet.  The mapping is either the standard A-Z mapping or ROT-13,
seemingly indicated by the suit.  At least some of the sentence
fragements are from Rush's Tom Sawyer.

Badges also have a 3-digit binary number on the back.  Some badges also
depict a simple number generator that produces the following sequences.

      +-------+
      v       |
              |
    000 (0) --+

    001 (1) <-+
    100 (4)   |
    010 (2)   |
    101 (5)   |
    110 (6)   |
    111 (7)   |
    011 (3) --+

e, pi and a circular icon also appear on different suits instead of the circuit.
http://en.wikipedia.org/wiki/Euler%27s_identity could connect them.

EOF

for f in *.txt; do
    suit=`echo $f | sed 's/\(......\).*/\1/'`
    number=`echo $f | sed 's/......_\([^-]*\).*/\1/'`
    binary=`echo $f | sed 's/......_[^-]*-\(...\).*/\1/'`
    printf "$suit$binary|%2s-$suit " $number
    ./decode $f
done | sort | sed 's/.\{10\}/    /' >>$out
